name: Security Scanning

on:
  pull_request:
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  dependency-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Enable NuGet cache
      uses: actions/cache@v3.0.11
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    - name: Restore Solution
      run: dotnet restore Aide.ClinicalReview.Service.sln
      working-directory: ./src

    - name: Dependency Scan
      run: |
        dotnet list package --vulnerable 2>&1 | tee vulnerable.txt
        echo "Analyzing dotnet list package command log output..."
        sh -c "! grep 'has the following vulnerable packages' vulnerable.txt"
      working-directory: ./src

